# .github/release.yml

changelog:
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Enhancements
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug-fix
    - title: DevOps
      labels:
        - DevOps
    - title: Housekeeping
      labels:
        - housekeeping
    - title: Architecture
      labels:
        - architecture    
    - title: Documentation
      labels:
        - documentation
